<?php

return [
    App\Providers\AppServiceProvider::class,
    App\Providers\BusinessEntityTypeServiceProvider::class,
    App\Providers\BusinessScaleServiceProvider::class,
    App\Providers\DepartmentServiceProvider::class,
    App\Providers\DistrictServiceProvider::class,
    App\Providers\EducationServiceProvider::class,
    App\Providers\GradeLevelServiceProvider::class,
    App\Providers\InstitutionServiceProvider::class,
    App\Providers\InvestmentTypeServiceProvider::class,
    App\Providers\KbliServiceProvider::class,
    App\Providers\ObservationServiceProvider::class,
    App\Providers\PositionServiceProvider::class,
    App\Providers\ProvinceServiceProvider::class,
    App\Providers\RankServiceProvider::class,
    App\Providers\RecommendationServiceProvider::class,
    App\Providers\RoleServiceProvider::class,
    App\Providers\SubDistrictServiceProvider::class,
    App\Providers\SubSectorServiceProvider::class,
    App\Providers\UserServiceProvider::class,
    App\Providers\ActivityServiceProvider::class,
    App\Providers\VillageServiceProvider::class,
];
