services:
    mysql:
        container_name: sipkansv_mysql
        image: mysql:8.4.0
        ports:
            - "${DB_PORT}:3306"
        volumes:
            - sipkansv_db_data:/var/lib/mysql
        environment:
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
        networks:
            - sipkansv

    adminer:
        container_name: sipkansv_adminer
        image: adminer:latest
        restart: always
        ports:
            - "9000:8080"
        networks:
            - sipkansv
        depends_on:
            - mysql

volumes:
    sipkansv_db_data:
        name: sipkansv_db_data

networks:
    sipkansv:
        name: sipkansv
        driver: bridge
