services:
    mysql:
        container_name: sipkansv_mysql
        image: mysql:8
        ports:
            - "${DB_PORT}:3306"
        volumes:
            - sipkansv_db_data:/var/lib/mysql
        environment:
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
        networks:
            - sipkansv

volumes:
    sipkansv_db_data:
        name: sipkansv_db_data

networks:
    sipkansv:
        name: sipkansv
        driver: bridge
