services:
    mysql:
        container_name: sipkpsv_mysql
        image: mysql:8
        ports:
            - "${DB_PORT}:3306"
        volumes:
            - sipkpsv_db_data:/var/lib/mysql
        environment:
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
        networks:
            - sipkpsv

volumes:
    sipkpsv_db_data:
        name: sipkpsv_db_data

networks:
    sipkpsv:
        name: sipkpsv
        driver: bridge
